"""Collect (state, browser frame) calibration pairs for the native renderer.

For each sampled state: reset the browser env to it, save the RAW two-pane
frame (obs mode "raw" — no DINO, no JPEG re-encode beyond lossless PNG) plus
the requested state and the OBSERVED post-settle viewer state (NG may
normalize values — the observed one is ground truth for the native render).
Each state is reset TWICE: the a/b frame pair measures the browser's own
re-render variance, the yardstick pixel-level parity is judged against.

States are generated by the training provider itself (FlywireSkeletonProvider
with explicit segment_id: same node/orientation/zoom sampling as training,
curriculum bypassed), over eval-pool segments.

Runs against the MAIN neurogym-agent checkout's venv/config (only stable
APIs used); the script itself lives on the native-renderer branch.

    uv run --no-sync python /path/to/worktree/native/collect_pairs.py \
        --config configs/ppo_zmax_navigate.yaml \
        --pool eval_d0_v1.parquet --n-states 300 \
        --out-dir /scratch/kp0374/native_spike/pairs_v1
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import sys

import numpy as np
import pyarrow.parquet as pq
from PIL import Image


class EpisodeTimeout(Exception):
    pass


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/ppo_zmax_navigate.yaml")
    ap.add_argument("--pool", default="eval_d0_v1.parquet")
    ap.add_argument("--n-states", type=int, default=300)
    ap.add_argument("--n-segments", type=int, default=12)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    os.environ.setdefault("RAY_ENABLE_UV_RUN_RUNTIME_ENV", "0")
    from ngllib_agent.env_build import build_env, load_config
    from ngllib_agent.providers import FlywireSkeletonProvider

    cfg = load_config(args.config)
    cfg.setdefault("obs", {})["mode"] = "raw"

    def make_env():
        return build_env(cfg)

    env = make_env()

    signal.signal(signal.SIGALRM, lambda *_: (_ for _ in ()).throw(EpisodeTimeout()))

    ec = cfg["env"]
    psr = ec.get("projection_scale_range")
    provider = FlywireSkeletonProvider(
        ec["parquet_path"],
        projection_scale_range=tuple(psr) if psr else None)

    pool = pq.read_table(args.pool).to_pylist()
    rng = np.random.default_rng(args.seed)
    idx = rng.choice(len(pool), size=args.n_segments, replace=False)
    seg_ids = [str(pool[int(i)]["root_id"]) for i in idx]
    print(f"[collect] segments: {seg_ids}", flush=True)

    os.makedirs(os.path.join(args.out_dir, "frames"), exist_ok=True)
    records = []
    i = 0
    while i < args.n_states:
        rid = seg_ids[i % len(seg_ids)]
        state, task_info = provider(rng, {"segment_id": rid})
        rec = {"idx": i, "root_id": rid, "requested_state": state,
               "task_info": task_info}
        ok = True
        for tag in ("a", "b"):
            signal.alarm(420)
            try:
                obs, _ = env.reset(options={"state": state,
                                            "task_info": task_info})
            except EpisodeTimeout:
                print(f"[collect] state {i}{tag}: WEDGED — rebuilding env, "
                      "skipping state", flush=True)
                signal.alarm(30)
                try:
                    env.close()
                except Exception:
                    pass
                finally:
                    signal.alarm(0)
                env = make_env()
                ok = False
                break
            finally:
                signal.alarm(0)
            Image.fromarray(np.asarray(obs["image"], dtype=np.uint8)).save(
                os.path.join(args.out_dir, "frames", f"{i:04d}_{tag}.png"))
            rec[f"observed_{tag}"] = {
                "position": np.asarray(obs["position"]).tolist(),
                "orientation": np.asarray(obs["orientation"]).tolist(),
                "xs_scale": float(np.asarray(obs["xs_scale"]).ravel()[0]),
                "proj_scale": float(np.asarray(obs["proj_scale"]).ravel()[0]),
            }
        if not ok:
            continue
        records.append(rec)
        if (i + 1) % 10 == 0:
            with open(os.path.join(args.out_dir, "states.jsonl"), "w") as f:
                for r in records:
                    f.write(json.dumps(r) + "\n")
            print(f"[collect] {i + 1}/{args.n_states}", flush=True)
        i += 1

    with open(os.path.join(args.out_dir, "states.jsonl"), "w") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")
    env.close()
    print(f"[collect] wrote {len(records)} state pairs -> {args.out_dir}",
          flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
